### ISSUE TITLE
Not able to run the project.

### ISSUE THREAD

**Issue by mayureshs** [ifeanyidike/react-native-material-design#1]
Are there any custom instructions to start the app ? I cloned it and did npm start but the expo simulator does not run in the browser to open in an Android simulator or iPhone with Expo client.

**Comment by ifeanyidike** [comment]
There are no custom instructors. The problem might be with your expo simulator. Make sure you have the correct version and ensure that everything is configured correctly.

**Comment by mayureshs** [comment]
![Capture](https://user-images.githubusercontent.com/1014702/95520726-8f0d8a00-098d-11eb-9ad1-433984dece0e.JPG)
This is what I get after npm install and npm start

**Comment by ifeanyidike** [comment]
Out of curiosity, I went ahead and cloned the repository again. I corrected a few things in the App.js file. Everything is working fine in my computer. Please clone the repository again, run 'npm install', and then 'expo start'. Thanks

**Comment by mayureshs** [comment]
Thank you
